feat: add fonts
pdabrowsky/react-nowness-training pull request #13
Opened 2022-08-16 08:26 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202789294700854/f

2022-08-16 08:45 UTC, dominikx96 requested changes

2022-08-16 08:45 UTC, dominikx96 commented on src/styles/_base.scss
> +    font-family: 'Futura';
👀 
1. You shouldn't use @font-face inside a body, it doesn't make sense
2. Read a task description in Asana and implement techniques from the description, elaborate on why we should use a preload
3. Why did you set `Futura` as a font? As you can see a few lines above, there is a font name: `Futura PT`
4. Add the second font (native, it can be arial), and elaborate why the second font is necessary

2022-08-16 09:46 UTC, pdabrowsky commented on src/styles/_base.scss
> +    font-family: 'Futura';
We should use preload because fonts are usually pulled late in the loading process of a website. If there’s a connection issue and the fonts aren’t downloaded, the page will render using generic system fonts. Then, once the fonts have been downloaded, the page will re-render.

2022-08-16 09:54 UTC, pdabrowsky commented on src/styles/_base.scss
> +    font-family: 'Futura';
Second font is necessary because if the first font will not be loaded the second or next in the que will be loaded

2022-08-17 06:44 UTC, dominikx96 requested changes

2022-08-17 06:44 UTC, dominikx96 commented on src/styles/App.scss
> +    font-family: 'Futura PT';
Use a variable to set font-family.

2022-08-17 06:44 UTC, dominikx96 commented on src/stories/button.css
> +  font-family: 'Futura';
Use a variable to set font-family.

2022-08-17 07:24 UTC, dominikx96 approved these changes

2022-08-17 07:24 UTC, merged