feat: main header
pdabrowsky/react-nowness-training pull request #16
Opened 2022-08-23 11:35 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705556727675/f

2022-08-24 07:33 UTC, dominikx96 commented
@pdabrowsky why did you force push that?

![Screenshot 2022-08-24 at 09 26 19](https://user-images.githubusercontent.com/16655908/186358438-2e20e34d-ad16-4766-9138-a2a2b201fa10.png)

2022-08-25 07:30 UTC, dominikx96 requested changes
It doesn't look like as on designs, please check again and ask for review once you test that end to end

2022-08-25 07:30 UTC, dominikx96 commented on src/assets/Logo/Logo.tsx
> +import type { LogoProps } from './Logo.types';
You can store this logo as .svg file, we don't need that as a component

2022-08-25 07:30 UTC, dominikx96 commented on src/assets/Logo/Logo.types.ts
> +};
if you change a logo to svg, it's not necessary

2022-08-25 07:30 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +            </Button>
please add a onClick handler with console.log

2022-08-25 07:30 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.scss
> +  height: 24px;
You don't need to hardcode height

2022-08-25 07:30 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +          </li>
Create an array with these elements, define types and map that array to a component, you don't need to repeat a code

2022-08-25 07:30 UTC, dominikx96 commented on src/components/SocialHeader/SocialHeader.tsx
>            </a>
As above, do not repeat that code

2022-08-29 06:41 UTC, dominikx96 requested changes
It should be overflow auto, currently I always have a visible scroll bar:
![Screenshot 2022-08-29 at 08 29 25](https://user-images.githubusercontent.com/16655908/187138910-f2853bb7-ecf9-413d-b063-8e516f7dca24.png)

It looks like, these borders overlap:
![Screenshot 2022-08-29 at 08 29 32](https://user-images.githubusercontent.com/16655908/187139022-d743ecad-c29e-4e47-b8fb-1818d8a9a006.png)

2022-08-29 06:41 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.scss
> +.main-header--border {
Why have you used `--`? It 's BEM modificator and should be used if you e.g. create a new component variant 🤔

2022-08-29 06:41 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +          <Burger className="main-header__burger" />
Add the `onClick` callback with `console.log`

2022-08-29 06:41 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +              <li key={id}>
Using `index` is not a good practice use as a key, please elaborate why

2022-08-29 06:41 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +  const naviagtion = ['series', 'topics', 'picks', 'special programs', 'nowness awards', 'events'];
It should have a structure `id, label, url`

2022-08-29 07:31 UTC, pdabrowsky commented on src/components/MainHeader/MainHeader.tsx
> +              <li key={id}>
Using index can negatively impact performance and may cause issues with component state.

2022-08-29 13:24 UTC, dominikx96 requested changes

2022-08-29 13:24 UTC, dominikx96 commented on src/components/SocialHeader/SocialHeader.tsx
> +  ];
Please hardcode ids there is no sense to increment and index here

2022-08-29 13:24 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +    { id: nextIndex, label: 'events', url: '/' },
same as below

2022-08-30 12:00 UTC, dominikx96 requested changes

2022-08-30 12:00 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +      <div className="main-header-border">
Why is it `border`? Also, you should follow BEM here and make sth like:
```
main-header__content
```

2022-08-30 12:00 UTC, dominikx96 commented on src/components/MainHeader/MainHeader.tsx
> +      <nav className="main-header-border">
Same as above

2022-08-30 13:05 UTC, dominikx96 approved these changes

2022-08-30 13:05 UTC, merged