Feat/artists hero
pdabrowsky/react-nowness-training pull request #17
Opened 2022-08-29 12:45 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705556786278/f

2022-08-29 13:40 UTC, dominikx96 requested changes
It doesn't look like on Figma:
![Screenshot 2022-08-29 at 15 37 34](https://user-images.githubusercontent.com/16655908/187214707-ad47bb7b-6d76-46f3-99ec-0df191d663d3.png)

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.tsx
> +          src={require('../../assets/img/background.jpg')}
👀 
https://create-react-app.dev/docs/adding-images-fonts-and-files

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.tsx
> +          alt="background"
It's a background and I don't think we should add an alt text, leave blank: https://help.siteimprove.com/support/solutions/articles/80000863904-accessibility-image-alt-text-best-practices

+ text is not descriptive, please correct this text: https://bighack.org/how-to-write-better-alt-text-descriptions-for-accessibility/

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.tsx
> +          <p>Back to Awards</p>
Use `span`

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.tsx
> +        src={require('../../assets/img/man.jpg')}
👀

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.tsx
> +        alt="background"
Incorrect alt text

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +}
It should be positioned by `bottom: -x px`, not %

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +}
and position absolute should have a wrapper with image and text, not only image

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +}
Please add a basic left/right animation on hover. Create a separate scss file to store keyframes - you should be able to reuse them

2022-08-29 13:40 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +  max-width: 1600px;
you don't need that

2022-08-30 12:14 UTC, dominikx96 requested changes

2022-08-30 12:14 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +}
Do not use absolute for everything! As I mentioned you should wrap this content with `Container` component and add position relative, that's everything :D

2022-08-30 12:14 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +  :hover {
You forgot about `&` and that's why it doesn't work

2022-08-30 12:14 UTC, dominikx96 commented on src/components/Hero/Hero.scss
> +  object-fit: cover;
👀  please elaborate what's objectFit position

2022-08-30 12:49 UTC, pdabrowsky commented on src/components/Hero/Hero.scss
> +  object-fit: cover;
objectFit position property sets how content (img or video) should be resized to fit its container.

2022-09-06 07:22 UTC, dominikx96 requested changes
just 2 small improvements, looks good!

2022-09-06 07:22 UTC, dominikx96 commented on src/styles/_variables.scss
>  $bold: 500;
It should have a `weight` prefix, it isn't clear to me what the `$light` variable means.

2022-09-06 07:22 UTC, dominikx96 commented on src/styles/_animations.scss
> +}
good job! 💪

2022-09-06 07:31 UTC, dominikx96 requested changes

2022-09-06 07:31 UTC, dominikx96 commented on src/components/Hero/Hero.tsx
> +const Hero = () => {
Do not hardcode props. Create props & types for:
- background image url
- artist name
- artist image

2022-09-07 09:10 UTC, dominikx96 approved these changes

2022-09-07 09:10 UTC, merged