feat/ artists artworks carousel
pdabrowsky/react-nowness-training pull request #19
Opened 2022-09-07 08:18 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705556893094/f

2022-09-22 12:12 UTC, dominikx96 requested changes

2022-09-22 12:12 UTC, dominikx96 commented on src/components/Artworks/Artworks.scss
> +  max-width: 1069px;
Other sections are in the same max-width as this one, so why haven't you used a container component?

2022-09-22 12:12 UTC, dominikx96 commented on src/components/Artworks/Artworks.scss
> +  }
You should use double `--`, it is a BEM modificator.

2022-09-22 12:12 UTC, dominikx96 commented on src/components/Artworks/Artworks.scss
> +}
You can move this to the `.swiper-slide`

2022-09-22 12:12 UTC, dominikx96 commented on src/components/Artworks/Artworks.scss
> +    height: 40px;
You can create a mixin `square` to set both sizes

2022-09-22 12:12 UTC, dominikx96 commented on src/components/common/NavigationButton/NavigationButton.tsx
> +    <div className={className}>
It should be a button, not a div

2022-09-22 12:12 UTC, dominikx96 commented on src/components/common/NavigationButton/NavigationButton.types.ts
> +export type Direction = 'left' | 'right';
Update this prop to `NavigationButtonDirection`, it would be hard to read props in a large projects without component prefix

2022-09-22 14:02 UTC, pdabrowsky commented on src/components/Artworks/Artworks.tsx
> +import '../../../node_modules/swiper/swiper.scss';
How can i change this awful node modules import ?

2022-09-22 14:11 UTC, pdabrowsky commented on src/components/Artworks/Artworks.scss
> +  justify-content: center;
There is slide jumping, you can especially see it when you drag slider in mobile view. How can i fix it?

2022-09-22 14:21 UTC, pdabrowsky commented on src/components/Artworks/Artworks.scss
> +}
hmm, i think that will be better to stay here, because i wanna move left only middle slide not all of them. I can move this code to the `.swiper-slide` but i must change `&-prev {` styles cuz all slides will be moved.

2022-09-26 09:32 UTC, dominikx96 approved these changes

2022-09-26 09:32 UTC, merged