Feat/artists interview
pdabrowsky/react-nowness-training pull request #20
Opened 2022-09-08 17:05 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705557156584/f

2022-09-13 09:20 UTC, dominikx96 requested changes

2022-09-13 12:57 UTC, pdabrowsky commented on src/components/Interview/Interview.scss
> +  padding-bottom: 10px;
margin is used to create a space between elements, but the padding for example for the inner space line from the border

2022-09-14 15:35 UTC, dominikx96 approved these changes

2022-09-14 15:35 UTC, dominikx96 commented on src/components/Interview/Interview.scss
> +
💪

2022-09-14 15:35 UTC, dominikx96 commented
@pdabrowsky please resolve conflicts, I approved this PR

2022-09-15 09:56 UTC, merged