Feat/artists copyright
pdabrowsky/react-nowness-training pull request #23
Opened 2022-09-12 13:23 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705607514903/f

2022-09-13 09:42 UTC, dominikx96 requested changes

2022-09-13 09:42 UTC, dominikx96 commented on src/components/Copyright/Copyright.scss
> +  margin-bottom: 24px;
As I mentioned here: https://github.com/pdabrowsky/react-nowness-training/pull/22#pullrequestreview-1105460237 do not hardcode margin here

2022-09-13 09:42 UTC, dominikx96 commented on src/components/Copyright/Copyright.scss
> +    gap: 242px;
👀 can you elaborate on why it's this colossal value?

2022-09-13 12:10 UTC, pdabrowsky commented on src/components/Copyright/Copyright.scss
> +    gap: 242px;
from figma:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/64170538/189895752-1ffaed2c-658c-4b05-86c9-7ba89f3f3b0e.png">
it looks like the same with less code then new variant container with hardcoded max-width

2022-09-14 07:58 UTC, pdabrowsky commented
Why does the text look different from the design? text and content are the same.

2022-09-14 15:45 UTC, dominikx96 requested changes
see a comment + resolve conflicts

2022-09-14 15:45 UTC, dominikx96 commented on src/components/Copyright/Copyright.scss
> +    gap: 242px;
nope, it's not a good idea to use a gap in this way. You can use the existing container and use `flex` to set proper positions. Figma is not a good source of CSS values :P

2022-09-19 07:13 UTC, dominikx96 approved these changes

2022-09-19 07:29 UTC, merged