feat: work with form
pdabrowsky/react-nowness-training pull request #24
Opened 2022-09-16 10:10 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705557275637/f

2022-09-21 13:10 UTC, dominikx96 requested changes
+ what's the valid phone number? I can't send the form 🤔 
+ make gaps between error and input smaller
![Screenshot 2022-09-21 at 15 08 40](https://user-images.githubusercontent.com/16655908/191512487-191b1c16-78ff-46d1-9e19-87417528be8b.png)

2022-09-22 08:10 UTC, pdabrowsky commented on src/components/Contact/Contact.scss
> +  max-width: 504px;
Valid number is like the example with` + `in the beginning `"+48112223344"`

2022-09-22 11:45 UTC, dominikx96 requested changes
almost good!

2022-09-22 11:45 UTC, dominikx96 commented on src/components/Contact/Contact.scss
> +.contact_background {
Should be 2 x `_`

2022-09-22 11:45 UTC, dominikx96 commented on src/components/Contact/Contact.scss
> +  //margin + header text line height
make this type comments next to related line, not at the bottom

2022-09-22 11:45 UTC, dominikx96 commented on src/components/common/Textarea/Textarea.types.ts
> +};
Name for this type should be `TextareaProps`, I also think we should follow pattern `ComponentNameXXX`

2022-09-26 09:44 UTC, dominikx96 requested changes
almost good 💪

2022-09-26 09:44 UTC, dominikx96 commented on src/components/Contact/Contact.tsx
> +        onSubmit={handleSubmit((data) => handleContactSubmit(data))}
You can update to:

```
onSubmit={handleSubmit(handleContactSubmit)}
```
The `data` property still is availabe in the `handleContactSubmit` function :)

2022-09-26 09:44 UTC, dominikx96 commented on src/components/common/Input/Input.stories.tsx
> +      classNames={{}}
Make this prop optional, you shouldn't provide this prop if you don't need this

2022-09-26 09:44 UTC, dominikx96 commented on src/components/common/Input/Input.tsx
> +  const { wrapper = '', input = '', labelClass = '' } = classNames;
If `classNames` will be optional, you can make:

```
const { wrapper = '', input = '', labelClass = '' } = classNames || {}
```

2022-09-26 09:44 UTC, dominikx96 commented on src/components/common/Textarea/Textarea.stories.tsx
> +      classNames={{}}
Same as above, do not provide an empty prop

2022-09-26 09:44 UTC, dominikx96 commented on src/components/common/Textarea/Textarea.tsx
> +  const { area = '', wrapper = '', labelClass = '' } = classNames;
```
|| {}
``

2022-09-29 08:48 UTC, dominikx96 approved these changes

2022-09-29 08:48 UTC, merged