added prettier config
pdabrowsky/react-nowness-training pull request #3
Opened 2022-08-03 08:18 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705605335921/f

2022-08-03 08:47 UTC, dominikx96 requested changes
It won't work, there is no prettier package. Please follow e.g. this tutorial: https://medium.com/@frontend-newbie/integrating-prettier-with-eslint-for-your-create-react-app-in-vscode-153ebe89c1a2

2022-08-03 08:48 UTC, dominikx96 commented
@pdabrowsky please also write down explanation why we should use eslint and prettier, what's the difference

2022-08-03 11:59 UTC, pdabrowsky commented
prettier - narzędzie służące do formatowania kodu, w configu można ustawić parametry które będą modyfikowanie podczas formatowania np. zamiana podwójnego cudzysłowu na pojedynczy czy wcięcia.

eslint - narzędzie służące do walidacji kodu na etapie pisania, dodatkowo można ustawić je aby weryfikowalo nasz kod przed np. commitem. Również posiada swój config w którym możemy dodawać reguły dzięki którym dostajemy ostrzegawcze warrningi czy errory.

2022-08-05 09:12 UTC, dominikx96 requested changes
You haven't installed prettier, it doesn't work.

2022-08-05 09:12 UTC, dominikx96 commented on .prettierrc
> +  "parser": "babel"
These 3 don't have any sense, do not copy and paste without understanding :) The `vueIndentScriptAndStyle` is related for vue,js not react projects. You can change this config to:

```
module.exports = {
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  trailingComma: 'all',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  singleAttributePerLine: true,
};
```

2022-08-05 09:21 UTC, pdabrowsky commented on .prettierrc
> +  "parser": "babel"
i copied default config from vscode, when i added external file, it overridden default

2022-08-05 09:24 UTC, pdabrowsky commented on .prettierrc
> +  "parser": "babel"
doesn't prettier install from react create app by default?

2022-08-05 09:38 UTC, dominikx96 commented on .prettierrc
> +  "parser": "babel"
- this local file has more priority, please replace that
- it works for you, but not me, you should always install a package locally because someone can have a different editor config, having a local package and defined config file gives you confidence that the code is formatted in the same way for each collabolator

2022-08-08 08:21 UTC, dominikx96 requested changes
Still it doesn't work. You've missed following packages:

```
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
```

Notice that installing these packages is not enough, please try to find a solution, sort it out and test.

2022-08-09 16:21 UTC, dominikx96 commented
You should add the 'plugin:prettier/recommended' into the `extends` array in the `.eslintrc` file.

2022-08-09 16:22 UTC, dominikx96 requested changes
You should add the 'plugin:prettier/recommended' into the extends array in the .eslintrc file.

Currently, the format command works as expected, but my VScode extension save on format - not. That's because there is no eslint plugin in the config file.

2022-08-10 13:43 UTC, dominikx96 approved these changes

2022-08-10 13:43 UTC, merged