added color palette and folder structure
pdabrowsky/react-nowness-training pull request #5
Opened 2022-08-04 14:25 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705556342442/f

2022-08-05 09:18 UTC, dominikx96 requested changes

2022-08-05 09:18 UTC, dominikx96 commented on .eslintrc.js
> +        extensions: [".scss", ".ts", ".tsx"],
Eslint doesn't lint your styles, you don't need the `.scss` extension here

2022-08-05 09:18 UTC, dominikx96 commented on src/Styles/_variables.scss
> +//color palette
- I don't think we need a comment here, it's obvious it's a color palette, doesn't give us any value
- make `styles` directory lowercase

2022-08-05 09:18 UTC, dominikx96 commented on src/Styles/_variables.scss
> +
I think we have more colors like gray and light black

2022-08-05 09:18 UTC, dominikx96 commented on src/Styles/index.scss
> +body {
- You should import the variables file here and then import the `index.scss` in the `App` component
-

2022-08-05 09:18 UTC, dominikx96 commented on src/Styles/index.scss
> +
Move these default styles into `_base.scss` and import that in the `index.scss`

2022-08-08 07:52 UTC, dominikx96 requested changes
This code doesn't work for me. Please fix errors, you should request a review once you test your changes. 

Follow docs to resolve a problem with sass: https://create-react-app.dev/docs/adding-a-sass-stylesheet

<img width="1972" alt="Screenshot 2022-08-08 at 09 50 59" src="https://user-images.githubusercontent.com/16655908/183367538-2d17030e-feb9-4fe3-81c7-2a0df97e7ea2.png">

2022-08-08 07:52 UTC, dominikx96 commented on src/Styles/_variables.scss
> +$gradient: linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7));
What about a situation when you'll have more than one gradient? Update this name :)

2022-08-09 16:33 UTC, dominikx96 requested changes
I assume you haven't tested that:
<img width="1194" alt="Screenshot 2022-08-09 at 18 32 37" src="https://user-images.githubusercontent.com/16655908/183707529-217ce509-98eb-42f4-af8b-eadb786edbcf.png">

Please test before requesting a review:
- Add a text into the `App` component
- Style that text to be in $gold color

2022-08-10 08:48 UTC, pdabrowsky commented
I tested it, i think it works. It didn't work for you because you didn't specify the source file.

2022-08-10 12:57 UTC, dominikx96 approved these changes

2022-08-10 12:57 UTC, merged