implemented commits linter
pdabrowsky/react-nowness-training pull request #7
Opened 2022-08-05 08:19 UTC by pdabrowsky

https://app.asana.com/0/1202705605335915/1202705605335925/f

2022-08-05 09:24 UTC, dominikx96 requested changes
Partially ok, but a couple of things are missing:
- husky
- lint-staged

read more about that: https://laurieontech.com/posts/husky/

and elaborate here why we want to implement that in this way :)

2022-08-08 08:01 UTC, dominikx96 requested changes
Also, husky and commitlint don't work.

2022-08-08 08:24 UTC, pdabrowsky commented on package.json
> +      "eslint",
`--fix` flag automatically fix problems

2022-08-08 09:05 UTC, dominikx96 requested changes
Please write down short explanation how the 'lint-staged' work

2022-08-08 10:26 UTC, pdabrowsky commented
Anytime a js file is staged for a commit, lint-staged runs the ESLint linter with the:

-  `--cache` tells ESLint to only check changed files
-  `--fix` tells ESLint to automatically fix problems when possible

2022-08-08 10:33 UTC, pdabrowsky commented
Commitlint is a simple tool that lints commit messages and makes sure they follow a set of rules.

2022-08-09 16:42 UTC, dominikx96 requested changes
Doesn't work for me, once I try to commit with a valid structure, I am getting: 
<img width="734" alt="Screenshot 2022-08-09 at 18 41 34" src="https://user-images.githubusercontent.com/16655908/183709119-af5067f3-6bc3-4188-a41b-1bfb6e09c1ad.png">

2022-08-11 08:15 UTC, merged